# Generated by Django 5.0.2 on 2024-03-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('recipes', models.ManyToManyField(to='recipeapp.recipe')),
            ],
        ),
    ]
