# Generated by Django 5.0.2 on 2024-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_recipecategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipecategories',
            name='recipes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(to='recipeapp.recipecategories', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='recipecategories',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название категории'),
        ),
    ]
